### ISSUE TITLE
##[error]Variable <Build.DefinitionId> is empty

### ISSUE THREAD

**Issue by danquirk** [dmitryserbin/azdev-artifacts-tagger#5]
I'm just trying to use ArtifactsTagger for the first time with your ReleaseOrchestrator extension. I set up a Release pipeline with a single environment that has a single task for ArtifactsTagger using the Integrated Endpoint setting but it fails with the error in the title:

##[error]Variable <Build.DefinitionId> is empty

I assume I've done some simple configuration wrong but I can't figure out what. I added the DEBUG variable equal to artifacts-tagger:* but didn't get any additional log output. I was able to use ReleaseOrchestrator successfully.

**Comment by dmitryserbin** [comment]
This is happening because you're using `ArtifactsTagger` in a release pipeline. The task can only be used in a build or milti-stage pipeline as it tags **build** artifact. The error you see indicates that the task simply can't find build ID which does not exist in a release pipeline.

I might add a restriction to the task to be used in the build pipelines only.

**Comment by danquirk** [comment]
Thanks for the quick follow up. I had suspected as much initially and tried it in a build pipeline rather than a release pipeline and got a similar but different error (with no additional debug logging):
```##[error]Variable <Build.DefinitionId> is empty```
which is what lead me to thinking I was missing some more fundamental config/setup step like permissions. I just have the following yml in the pipeline:

```
  - task: dmitryserbin.artifacts-tagger.artifacts-tagger.artifactstagger@1
    displayName: 'Tag Release Artifact'
    inputs:
      StageNameTag: false
      CustomTags: '$(MyBranch)/$(MyBuildNumber)'
```

I'm just trying to use these two extensions for exactly the scenario I saw you describe elsewhere. I'm imagining I will have a build pipeline which creates an artifact tagged with $(MyBranch)/$MyBuildNumber). That build pipeline will be an input artifact for numerous Release pipelines. Then I will have 1 orchestrator Release pipeline which also takes that build pipeline as an input artifact and kicks off all the other Release pipelines using the same tagged artifact so they're all running against the same build number.

**Comment by dmitryserbin** [comment]
Sorry for late reply. I think my first comment was misleading, not sure why said it, but let me correct myself.

The task works in a **release pipeline** and tags connected to the pipeline **build artifact**.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/30379061/77833003-007aad80-719f-11ea-9168-c80ebda39874.png">

When executed, the task updates tags on the target build artifact as configured.

<img width="877" alt="image" src="https://user-images.githubusercontent.com/30379061/77833058-4d5e8400-719f-11ea-9a2f-b9187e80e0ca.png">

I have a feeling it doesn't work for you because you're using YAML release pipeline instead of classic release pipeline. [Classic](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops&tabs=batch) & [YAML](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml) pipelines have different pre-defined variables (at very least). The task needs `Build.DefinitionId` value to detect connected artifact build pipeline ID.

<img width="971" alt="image" src="https://user-images.githubusercontent.com/30379061/77833139-e5f50400-719f-11ea-9d61-cee584110521.png">

Don't think I ever tested `ArtifactsTagger` with YAML pipelines, so it's safe to say it's not supported at the moment.

Please confirm if you're using YAML pipeline and try classic release pipeline instead?

**Comment by danquirk** [comment]
I'm not using YAML pipelines for this yet although I would like to be able to in the future.

I see my mistake now, seems obvious in retrospect but probably would be useful for the docs to have a full example of using ArtifactsTagger and ReleaseOrchestrator in concert. You've made a very nice little workflow here that I imagine a lot of people would find handy if they knew about it :) The error that Build.DefinitionId is null was correct because I didn't have an input artifact specified in the release pipeline that was using ArtifactsTagger.

The misunderstanding I had was conceptually I thought ArtifactsTagger would be used by the build/release pipeline which creates the artifact to tag its artifact at build time so that anyone could later try to use that artifact by tag. I see now the design is that the release pipeline using ReleaseOrchestrator should have the desired build pipeline as an input artifact, use ArtifactsTagger to tag that build artifact based on whatever variable/input artifact is chosen, and then use ReleaseOrchestrator to trigger other releases which also use that same build pipeline as an input.

**Comment by danquirk** [comment]
Closing since my issue was user error and you got me on the right track :)
